spring:
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**

  thymeleaf: 
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    encoding: utf-8
    content-type: text/html
    mode: HTML5


  datasource:
    informationSchema:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://38.75.137.228:10006/information_schema?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: uyAou673TYEuy@e63Ytw

    epg:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://38.75.137.228:10006/epg?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: uyAou673TYEuy@e63Ytw
      
    log:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://38.75.137.228:10006/log?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: uyAou673TYEuy@e63Ytw

    ds: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://38.75.137.228:10006/schedule_datasource?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: uyAou673TYEuy@e63Ytw

    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    waitTimeout: 300000000
    

server:
  port: 7070
  context-path: /satellite

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yim.satellite.domain

mapper: 
  mapper:
    identity: MYSQL
    not-empty: false

#logging:
#   level:
#     com:
#       iptv:
#         satellite:
#           dao: DEBUG